In [1]:
from skforecast.ForecasterAutoregMultiSeriesCustom import ForecasterAutoregMultiSeriesCustom
from skforecast.ForecasterAutoregMultiSeries import ForecasterAutoregMultiSeries
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np

In [2]:
FILEPATH = "tests/short_ts.csv"
sts = pd.read_csv(FILEPATH, parse_dates=[0])

In [336]:
reg = ForecasterAutoregMultiSeries(
    regressor=RandomForestRegressor(random_state=41),
    lags=2,
    series_weights={"1": 0.1, "2": 1.1, "3": 2.1}
)

In [311]:
filled_sts = sts.copy().fillna(0)
series = filled_sts

In [312]:
reg.fit(filled_sts, exog=pd.DataFrame({key: np.zeros(series.index.size) for key in "ABC"}))

/home/ywnien/py/IM1013/.IM1013/lib/python3.11/site-packages/skforecast/utils/utils.py:626: UserWarning: `y` has no DatetimeIndex nor RangeIndex index. Index is overwritten with a RangeIndex.
  warnings.warn(


In [ ]:
from sklearn.preprocessing import StandardScaler

In [190]:
res = reg.create_train_X_y(filled_sts, exog=pd.DataFrame({key: np.zeros(filled_sts.index.size) for key in "ABC"}))

/home/ywnien/py/IM1013/.IM1013/lib/python3.11/site-packages/skforecast/utils/utils.py:626: UserWarning: `y` has no DatetimeIndex nor RangeIndex index. Index is overwritten with a RangeIndex.
  warnings.warn(


In [4]:
l1 = [1, 2, 3, 4, 5]
l2 = [1, 2, 3]

In [9]:
%%timeit
[element for element in l1 if element not in l2]

762 ns ± 96.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [10]:
%%timeit
list(set(l1) ^ set(l2))

1.09 µs ± 174 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [12]:
import numpy as np

In [13]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

list_2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]

In [1]:
from tstide.transformer import _rearrange

tst = _rearrange.main()
tst, X = tst

In [2]:
X, tst.X_columns

(array([[[ 11., 100., 200.,   0.],
         [ 21., 100., 200.,   1.],
         [ 31., 100., 200.,   2.]],
 
        [[ 42., 110., 210.,   3.],
         [ 52., 110., 210.,   4.],
         [ 62., 110., 210.,   5.]],
 
        [[ 52., 110., 210.,   4.],
         [ 62., 110., 210.,   5.],
         [ 72., 110., 210.,   6.]],
 
        [[ 63., 120., 220.,   5.],
         [ 73., 120., 220.,   6.],
         [ 83., 120., 220.,   7.]]]),
 ['lag_3', 'lag_2', 'lag_1', 'var_1', 'exog1', 'exog2'])

In [10]:
import pandas as pd
from IPython.display import display
display(pd.DataFrame(X, columns=tst.X_columns))
display(pd.DataFrame(tst.y, columns=tst.y_columns))


lag_3  lag_2  lag_1  var_1  exog1  exog2
0   11.0   21.0   31.0    3.0  100.0  200.0
1   42.0   52.0   62.0    6.0  110.0  210.0
2   52.0   62.0   72.0    7.0  110.0  210.0
3   63.0   73.0   83.0    8.0  120.0  220.0

step_1
0      41
1      72
2      82
3      93

In [79]:
res_ = []
for _ in range(2):
    res = []
    for _ in range(10):
        res.append(array_2d)
    res_.append(np.vstack(res))
np.vstack(res_)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4,

# Pipeline object

In [75]:
from sklearn.base import BaseEstimator, TransformerMixin
import pandas as pd
import numpy as np
from numpy.random import randint
from sklearn.pipeline import make_pipeline

class Dispatcher(BaseEstimator, TransformerMixin):
    # def __init__(self, name: str) -> None:
    #     self.name = name
    
    def register(self, value):
        self.__value = value
    
    def fit(self, X, y=None):
        return self
    
    def transform(self, y):
        return self.value
    
    @property
    def getter_test(self):
        return self.__value
        

class CustomTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, dispatcher: Dispatcher):
        self.dispatch = dispatcher

    def fit(self, X, y=None):
        return self

    def transform(self, X, y=None):
        # Perform arbitary transformation
        X["random_int"] = randint(0, 10, X.shape[0])
        y = randint(100, 110, X.shape[0])
        self.dispatch.register(y)
        # self.sticky = 28
        return X


# ct = CustomTransformer()
# ct.transform(pd.DataFrame(range(10)))
dispatcher = Dispatcher()
pipe = make_pipeline(CustomTransformer(dispatcher))
pipe.fit_transform(pd.DataFrame(range(10)), range(10))

0  random_int
0  0           1
1  1           5
2  2           5
3  3           0
4  4           7
5  5           5
6  6           7
7  7           1
8  8           3
9  9           0

In [65]:
# dispatcher.value

array([106, 109, 101, 100, 105, 103, 101, 106, 100, 105])

# FeatureUnion

In [72]:
from sklearn.pipeline import FeatureUnion
from sklearn.decomposition import PCA, TruncatedSVD
union = FeatureUnion([
    ("pca", PCA(n_components=1)),
    ("svd", TruncatedSVD(n_components=2))
])
X = [[0., 1., 3], [2., 2., 5]]
union.fit_transform(X)

array([[ 1.5       ,  3.03954967,  0.87243213],
       [-1.5       ,  5.72586357, -0.46312679]])

# MultiSeriesCustom

In [156]:
test_frame = pd.DataFrame({"A": np.arange(40), "B": np.arange(40) + 10, "C": np.arange(40) + 10})

def create_predictors(y):
    """
    Create first 10 lags of a time series.
    Calculate moving average with window 20.
    """

    lags = y[-1:-11:-1]     # window_size = 10
    mean = np.mean(y[-20:]) # window_size = 20
    predictors = np.hstack([lags, mean])

    return predictors

In [247]:
from skforecast.utils import check_y, preprocess_y
# series = data_train
# window_size = 20
# fun_predictors = create_predictors
series = filled_sts
window_size = 3
fun_predictors = lambda y: np.hstack([y[-2:], np.mean(y[-2:])])

X_levels = []
expected = []
for i, serie in enumerate(series.columns):
    y = series[serie]
    check_y(y=y)
    # NOTE: Encoders part
    # y = transform_series(
    #     series            = y,
    #     transformer       = self.transformer_series_[serie],
    #     fit               = True,
    #     inverse_transform = False
    # )

    y_values, y_index = preprocess_y(y=y) # 其實在給我做型態檢查，根本沒有preprocess :(

    temp_X_train  = []
    temp_y_train  = []

    for j in range(len(y) - window_size): # 把 1d time series 切成好幾段，變成要輸入的 X, y

        train_index = np.arange(j, window_size + j)
        test_index  = window_size + j

        temp_X_train.append(fun_predictors(y=y_values[train_index]))
        temp_y_train.append(y_values[test_index])

    X_train_values = np.vstack(temp_X_train)
    y_train_values = np.array(temp_y_train)

    if np.isnan(X_train_values).any():
        raise ValueError(
            f"`fun_predictors()` is returning `NaN` values for series {serie}."
        )

    if i == 0:
        X_train = X_train_values
        y_train = y_train_values
    else:
        X_train = np.vstack((X_train, X_train_values))
        y_train = np.append(y_train, y_train_values)

    X_level = [serie]*len(X_train_values)
    X_levels.extend(X_level)

# NOTE: name_predictors part. Meaning is not clear so far

# y_values correspond only to the last series of `series`. Since the columns
# of X_train are the same for all series, the check is the same.
# 這寫法真糟，強制使用 array[-n:] 取值，不然檢查會失敗 :(
expected = fun_predictors(y_values[:-1])
observed = X_train[-1, :]

if expected.shape != observed.shape or not (expected == observed).all():
    raise ValueError(
        (
            f"The `window_size` argument ({window_size}), declared when "
            f"initializing the forecaster, does not correspond to the window "
            f"used by `fun_predictors()`."
        )
    )

/home/ywnien/py/IM1013/.IM1013/lib/python3.11/site-packages/skforecast/utils/utils.py:626: UserWarning: `y` has no DatetimeIndex nor RangeIndex index. Index is overwritten with a RangeIndex.
  warnings.warn(


# 真的能動???

In [160]:
# Libraries
# ==============================================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from skforecast.ForecasterAutoregCustom import ForecasterAutoregCustom
from skforecast.ForecasterAutoregMultiSeriesCustom import ForecasterAutoregMultiSeriesCustom
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from skforecast.model_selection import bayesian_search_forecaster

In [161]:
# Data download
# ==============================================================================
url = ('https://raw.githubusercontent.com/JoaquinAmatRodrigo/skforecast/master/'
       'data/simulated_items_sales.csv')
data = pd.read_csv(url, sep=',')

# Data preparation
# ==============================================================================
data['date'] = pd.to_datetime(data['date'], format='%Y-%m-%d')
data = data.set_index('date')
data = data.asfreq('D')
data = data.sort_index()
data.head()

item_1     item_2     item_3
date                                       
2012-01-01   8.253175  21.047727  19.429739
2012-01-02  22.777826  26.578125  28.009863
2012-01-03  27.549099  31.751042  32.078922
2012-01-04  25.895533  24.567708  27.252276
2012-01-05  21.379238  18.191667  20.357737

In [162]:
# Split data into train-val-test
# ==============================================================================
end_train = '2014-07-15 23:59:00'
data_train = data.loc[:end_train, :].copy()
data_test  = data.loc[end_train:, :].copy()

print(
    f"Train dates : {data_train.index.min()} --- {data_train.index.max()}  "
    f"(n={len(data_train)})"
)
print(
    f"Test dates  : {data_test.index.min()} --- {data_test.index.max()}  "
    f"(n={len(data_test)})"
)

Train dates : 2012-01-01 00:00:00 --- 2014-07-15 00:00:00  (n=927)
Test dates  : 2014-07-16 00:00:00 --- 2015-01-01 00:00:00  (n=170)


In [163]:
# Custom function to create predictors
# ==============================================================================
def create_complex_predictors(y):
    """
    Create first 10 lags of a time series.
    Calculate moving average with window 20.
    """

    lags = y[-1:-11:-1]     # window_size = 10  
    mean = np.mean(y[-20:]) # window_size = 20
    predictors = np.hstack([lags, mean])

    return predictors

In [166]:
# Create and fit forecaster
# ==============================================================================
forecaster = ForecasterAutoregMultiSeriesCustom(
                 regressor       = RandomForestRegressor(random_state=123),
                 fun_predictors  = create_complex_predictors,
                 name_predictors = [f'lag {i}' for i in range(1, 11)] + ['moving_avg_20'],
                 window_size     = 21 # window_size needed by the mean is the most restrictive one
             )

forecaster.fit(series=data_train)

In [ ]:
from skforecast.ForecasterAutoregMultiSeries import ForecasterAutoregMultiSeries
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor
from skforecast.model_selection_multiseries import random_search_forecaster_multiseries
# Data download
# ==============================================================================
url = (
       'https://raw.githubusercontent.com/JoaquinAmatRodrigo/skforecast/master/'
       'data/simulated_items_sales.csv'
)
data = pd.read_csv(url, sep=',')

# Data preparation
# ==============================================================================
data['date'] = pd.to_datetime(data['date'], format='%Y-%m-%d')
data = data.set_index('date')
data = data.asfreq('D')
data = data.sort_index()
data.head()

# Create and fit forecaster multi series
# ==============================================================================
forecaster = ForecasterAutoregMultiSeries(
                 regressor          = RandomForestRegressor(random_state=123),
                 lags               = 24,
             )

lags_grid = [3, 5]

# Regressor hyperparameters
param_distributions = {
    'n_estimators': np.arange(start=10, stop=100, step=1, dtype=int),
    'max_depth': np.arange(start=5, stop=30, step=1, dtype=int)
}



In [78]:
from typing import Callable, Optional, Union, Any
import numpy as np


class NewForecaster(ForecasterAutoregMultiSeries):
    def __init__(self, regressor: object, lags: int | np.ndarray | list, transformer_series: object | dict | None = None, transformer_exog: object | None = None, weight_func: Callable[..., Any] | dict | None = None, series_weights: dict | None = None, forecaster_id: str | int | None = None) -> None:
        super().__init__(regressor, lags, transformer_series, transformer_exog, weight_func, series_weights, forecaster_id)
        self.__name__ = "Fake"
    @staticmethod
    def __dummy_function():
        print("dummy")

# NewForecaster.__name__ = "FakeForecasterAutoregMultiSeries"
nf = NewForecaster(RandomForestRegressor(), 2)

# Causal model

In [11]:
import numpy as np

def generate_time_series(batch_size, n_steps):
    freq1, freq2, offsets1, offsets2 = np.random.rand(4, batch_size, 1)
    time = np.linspace(0, 1, n_steps)
    series = 0.5 * np.sin((time - offsets1) * (freq1 * 10 + 10))
    series += 0.2 * np.sin((time - offsets2) * (freq2 * 10 + 10))
    series += 0.1 * (np.random.rand(batch_size, n_steps) - 0.5)
    return series[..., np.newaxis].astype(np.float32)

batch_size = 10000
n_steps = 50
series = generate_time_series(batch_size, n_steps + 1)
X_train, y_train = series[:7000, :n_steps], series[:7000, -1]
X_valid, y_valid = series[7000:9000, :n_steps], series[7000:9000, -1]
X_test, y_test = series[9000:, :n_steps], series[9000:, -1]

In [12]:
series = generate_time_series(batch_size, n_steps + 10)
X_train, y_train = series[:7000, :n_steps], series[:7000, -10:, 0]
X_valid, y_valid = series[7000:9000, :n_steps], series[7000:9000, -10:, 0]
X_test, y_test = series[9000:, :n_steps], series[9000:, -10:, 0]

Y = np.empty((batch_size, n_steps, 10))
for step_ahead in range(1, 10 + 1):
    Y[:, :, step_ahead - 1] = series[:, step_ahead:step_ahead + n_steps, 0]
Y_train = Y[:7000]
Y_valid = Y[7000:9000]
Y_test = Y[9000:]

In [15]:
X_train.shape, y_train.shape

((7000, 50, 1), (7000, 10))

In [1]:
import numpy as np
from sklearn.ensemble import RandomForestRegressor

X = np.zeros([20, 5])
y = np.zeros([20, 5])
space = np.linspace(0, 2 * np.pi, 10 + 20)
space = np.sin(space)
for i in range(20):
    X[i] = space[i:i+5]
    y[i] = space[i+5:i+10]

In [16]:
reg = RandomForestRegressor()
reg.fit(X, y)


RandomForestRegressor()

In [7]:
import pandas as pd
df = pd.DataFrame(X)
df

0         1         2         3         4
0   0.000000  0.214970  0.419889  0.605174  0.762162
1   0.214970  0.419889  0.605174  0.762162  0.883512
2   0.419889  0.605174  0.762162  0.883512  0.963550
3   0.605174  0.762162  0.883512  0.963550  0.998533
4   0.762162  0.883512  0.963550  0.998533  0.986827
5   0.883512  0.963550  0.998533  0.986827  0.928977
6   0.963550  0.998533  0.986827  0.928977  0.827689
7   0.998533  0.986827  0.928977  0.827689  0.687699
8   0.986827  0.928977  0.827689  0.687699  0.515554
9   0.928977  0.827689  0.687699  0.515554  0.319302
10  0.827689  0.687699  0.515554  0.319302  0.108119
11  0.687699  0.515554  0.319302  0.108119 -0.108119
12  0.515554  0.319302  0.108119 -0.108119 -0.319302
13  0.319302  0.108119 -0.108119 -0.319302 -0.515554
14  0.108119 -0.108119 -0.319302 -0.515554 -0.687699
15 -0.108119 -0.319302 -0.515554 -0.687699 -0.827689
16 -0.319302 -0.515554 -0.687699 -0.827689 -0.928977
17 -0.515554 -0.687699 -0.827689 -0.928977 -0.986827
18 -0.687699 -0.827689 -0.928977 -0.986827 -0.998533
19 -0.827689 -0.928977 -0.986827 -0.998533 -0.963550

In [31]:
reg.fit(df, y)
reg.score(df, y)

0.9864778687296957

In [64]:
exog_col_names = {"totalFare", "ariline", "route", "departuretime"}
series_col_names = {"totalFare", "SeatsRemaining"}

In [70]:
%%timeit
if len(exog_col_names - series_col_names) != len(exog_col_names):
    pass

111 ns ± 1.16 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [71]:
%%timeit
if exog_col_names & series_col_names:
    pass

83.5 ns ± 0.257 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
